name: 3DMG
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - rdkit
  - pip
  - pip:
      - chemprop
      - torch-geometric
      - torch-scatter
